[package]
name = "declare-macro"
version = "0.1.0"
authors = ["l0calh05t <l0calh05t@gmx.net>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4.30"
syn = { version = "0.15.42", features = ["full"] }
quote = "0.6.13"
